services:
  vectoraidb:
    image: williamimoh/actian-vectorai-db:latest
    container_name: trace-vectoraidb
    ports:
      - "50051:50051"
    volumes:
      - ./backend/.vectordata:/data
    restart: unless-stopped
    stop_grace_period: 2m
